packages:
    - apps/*
    - functions/*
    - generated/*
    - libraries/*
    - ui/*
overrides:
    firebase: ^12.17.0
    firebase-admin: ^14.2.0
packageExtensions:
    "@generated/data-connector-web@*":
        peerDependencies:
            "@tanstack/react-query": ^5.0.0
allowBuilds:
    "@firebase/util": false
    "@nestjs/core": false
    "@parcel/watcher": false
    es5-ext: false
    esbuild: false
    nx: false
    protobufjs: false
    re2: false
    sharp: false
    unrs-resolver: false
minimumReleaseAge: 7200
