packages:
  - apps/plaster-calculator-web
  - functions/plaster-calculator-functions
allowBuilds:
  '@firebase/util': true
  protobufjs: true
  re2: true
  sharp: true
  unrs-resolver: true
blockExoticSubdeps: true
#trustPolicy: no-downgrade
minimumReleaseAge: 10080
