name: Deploy Storage

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - storage.rules

concurrency:
    group: deploy-storage
    cancel-in-progress: false

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment:
            name: storage
            url: https://console.firebase.google.com/project/plaster-calculator/storage
        steps:
            - uses: actions/checkout@v6

            - uses: pnpm/action-setup@v4
              with:
                  version: 10.24.0

            - uses: actions/setup-node@v6
              with:
                  node-version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Deploy Storage rules
              run: pnpm exec firebase deploy --only storage --project plaster-calculator --token "$FIREBASE_TOKEN"
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
